### ISSUE TITLE
选择题怎么应对

### ISSUE THREAD

**Issue by jcwsz6** [LiKe-rm/Useful-Scripts#1]
您好，首先谢谢作者，同时想问一下，针对选择题，怎么可以自动选择

**Comment by LiKe-rm** [comment]
好的，我周末有时间会更新一下，如果着急的话你可以先尝试问一下chatgpt2023-12-13 18:31:39>Lws 写道：

您好，首先谢谢作者，同时想问一下，针对选择题，怎么可以自动选择

**Comment by jcwsz6** [comment]
谢谢谢谢，不急的，大佬，我尝试了修改来着，奈何不是搞这个的，没成功。十分感谢回复与更新！

**Comment by jcwsz6** [comment]
谢谢作者！
